export const COMPANIES_DATA = [
  {
    id: 'comp_stripe',
    name: 'Stripe',
    slug: 'stripe',
    logo: 'https://www.google.com/s2/favicons?domain=stripe.com&sz=128',
    description: 'Stripe is a financial infrastructure platform for businesses. Millions of companies use Stripe to accept payments, grow revenue, and accelerate business opportunities globally.',
    website: 'https://stripe.com',
    industry: 'Financial Technology (FinTech)',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '354 Oyster Point Blvd' },
    companySize: '1,000+',
    foundedYear: 2010,
    verified: true,
  },
  {
    id: 'comp_google',
    name: 'Google',
    slug: 'google',
    logo: 'https://www.google.com/s2/favicons?domain=google.com&sz=128',
    description: 'Google’s mission is to organize the world’s information and make it universally accessible and useful. Building breakthroughs across Search, Cloud, DeepMind AI, Android, and YouTube.',
    website: 'https://google.com',
    industry: 'Internet & Cloud Computing',
    location: { city: 'Mountain View', state: 'CA', country: 'United States', address: '1600 Amphitheatre Parkway' },
    companySize: '10,000+',
    foundedYear: 1998,
    verified: true,
  },
  {
    id: 'comp_openai',
    name: 'OpenAI',
    slug: 'openai',
    logo: 'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
    description: 'OpenAI is an AI research and deployment company dedicated to ensuring that general-purpose artificial intelligence benefits all of humanity. Creators of GPT-4o, ChatGPT, and Sora.',
    website: 'https://openai.com',
    industry: 'Artificial Intelligence & Research',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '3180 18th St' },
    companySize: '1,000+',
    foundedYear: 2015,
    verified: true,
  },
  {
    id: 'comp_anthropic',
    name: 'Anthropic',
    slug: 'anthropic',
    logo: 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
    description: 'Anthropic is an AI safety and research company that builds reliable, interpretable, and steerable AI systems. Creators of Claude 3.5 Sonnet and Constitutional AI.',
    website: 'https://anthropic.com',
    industry: 'AI Safety & Large Language Models',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '548 Market St' },
    companySize: '500+',
    foundedYear: 2021,
    verified: true,
  },
  {
    id: 'comp_nvidia',
    name: 'NVIDIA',
    slug: 'nvidia',
    logo: 'https://www.google.com/s2/favicons?domain=nvidia.com&sz=128',
    description: 'NVIDIA pioneered accelerated computing to tackle challenges ordinary computers cannot solve. Powering global AI data centers, CUDA, Blackwell architectures, and Omniverse.',
    website: 'https://nvidia.com',
    industry: 'Semiconductors & AI Compute',
    location: { city: 'Santa Clara', state: 'CA', country: 'United States', address: '2788 San Tomas Expy' },
    companySize: '10,000+',
    foundedYear: 1993,
    verified: true,
  },
  {
    id: 'comp_microsoft',
    name: 'Microsoft',
    slug: 'microsoft',
    logo: 'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128',
    description: 'Microsoft enables digital transformation for the era of an intelligent cloud and an intelligent edge. Creators of Azure, Windows, VS Code, GitHub, and Microsoft 365 Copilot.',
    website: 'https://microsoft.com',
    industry: 'Enterprise Software & Cloud',
    location: { city: 'Redmond', state: 'WA', country: 'United States', address: 'One Microsoft Way' },
    companySize: '10,000+',
    foundedYear: 1975,
    verified: true,
  },
  {
    id: 'comp_apple',
    name: 'Apple',
    slug: 'apple',
    logo: 'https://www.google.com/s2/favicons?domain=apple.com&sz=128',
    description: 'Apple revolutionizes personal technology with iPhone, Mac, Apple Watch, iPad, and Apple Silicon. Building world-class consumer software and privacy-first engineering architectures.',
    website: 'https://apple.com',
    industry: 'Consumer Hardware & Operating Systems',
    location: { city: 'Cupertino', state: 'CA', country: 'United States', address: 'One Apple Park Way' },
    companySize: '10,000+',
    foundedYear: 1976,
    verified: true,
  },
  {
    id: 'comp_meta',
    name: 'Meta',
    slug: 'meta',
    logo: 'https://www.google.com/s2/favicons?domain=meta.com&sz=128',
    description: 'Meta builds technologies that help people connect, find communities, and grow businesses. Powering Instagram, WhatsApp, Llama open AI models, and Reality Labs.',
    website: 'https://meta.com',
    industry: 'Social Technologies & Open Source AI',
    location: { city: 'Menlo Park', state: 'CA', country: 'United States', address: '1 Hacker Way' },
    companySize: '10,000+',
    foundedYear: 2004,
    verified: true,
  },
  {
    id: 'comp_amazon',
    name: 'Amazon Web Services',
    slug: 'amazon-aws',
    logo: 'https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=128',
    description: 'Amazon Web Services (AWS) is the world’s most comprehensive and broadly adopted cloud platform, offering over 240 fully featured services from data centers globally.',
    website: 'https://aws.amazon.com',
    industry: 'Cloud Computing & Infrastructure',
    location: { city: 'Seattle', state: 'WA', country: 'United States', address: '410 Terry Ave N' },
    companySize: '10,000+',
    foundedYear: 2006,
    verified: true,
  },
  {
    id: 'comp_netflix',
    name: 'Netflix',
    slug: 'netflix',
    logo: 'https://www.google.com/s2/favicons?domain=netflix.com&sz=128',
    description: 'Netflix is one of the world’s leading entertainment services with over 270 million paid memberships. Pioneering high-concurrency microservices, video encoding, and recommendation ML.',
    website: 'https://netflix.com',
    industry: 'Media Streaming & Distributed Systems',
    location: { city: 'Los Gatos', state: 'CA', country: 'United States', address: '100 Winchester Circle' },
    companySize: '5,000+',
    foundedYear: 1997,
    verified: true,
  },
  {
    id: 'comp_figma',
    name: 'Figma',
    slug: 'figma',
    logo: 'https://www.google.com/s2/favicons?domain=figma.com&sz=128',
    description: 'Figma is the leading collaborative design and prototyping platform on the web. Powered by high-performance C++ WebAssembly, WebGL rendering, and multi-user CRDT synchronization.',
    website: 'https://figma.com',
    industry: 'Design Software & WebGL Engineering',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '760 Market St' },
    companySize: '1,000+',
    foundedYear: 2012,
    verified: true,
  },
  {
    id: 'comp_linear',
    name: 'Linear',
    slug: 'linear',
    logo: 'https://www.google.com/s2/favicons?domain=linear.app&sz=128',
    description: 'Linear is the purpose-built tool for modern software teams to streamline issues, sprints, and product roadmaps with sub-50ms latency and exceptional craftsmanship.',
    website: 'https://linear.app',
    industry: 'Developer Productivity & SaaS',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: 'Market Street' },
    companySize: '100+',
    foundedYear: 2019,
    verified: true,
  },
  {
    id: 'comp_vercel',
    name: 'Vercel',
    slug: 'vercel',
    logo: 'https://www.google.com/s2/favicons?domain=vercel.com&sz=128',
    description: 'Vercel provides the developer experience and infrastructure to build, scale, and secure a faster, more personalized web. Creators of Next.js, Turbopack, and v0.dev.',
    website: 'https://vercel.com',
    industry: 'Frontend Cloud & Web Frameworks',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '340 S Lemon Ave' },
    companySize: '500+',
    foundedYear: 2015,
    verified: true,
  },
  {
    id: 'comp_supabase',
    name: 'Supabase',
    slug: 'supabase',
    logo: 'https://www.google.com/s2/favicons?domain=supabase.com&sz=128',
    description: 'Supabase is the open-source Firebase alternative providing Postgres databases, authentication, instant Realtime subscriptions, Edge Functions, and vector storage.',
    website: 'https://supabase.com',
    industry: 'Open Source Cloud Databases',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: 'Remote Global' },
    companySize: '200+',
    foundedYear: 2020,
    verified: true,
  },
  {
    id: 'comp_cloudflare',
    name: 'Cloudflare',
    slug: 'cloudflare',
    logo: 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=128',
    description: 'Cloudflare protects and accelerates any Internet application online without adding hardware, installing software, or changing a line of code. Running on a global 300+ city edge network.',
    website: 'https://cloudflare.com',
    industry: 'Edge Computing & Cybersecurity',
    location: { city: 'Austin', state: 'TX', country: 'United States', address: '101 Townsend St' },
    companySize: '3,500+',
    foundedYear: 2009,
    verified: true,
  },
  {
    id: 'comp_airbnb',
    name: 'Airbnb',
    slug: 'airbnb',
    logo: 'https://www.google.com/s2/favicons?domain=airbnb.com&sz=128',
    description: 'Airbnb is a global travel community that offers end-to-end trips, including where you stay, what you do, and the people you meet across over 220 countries.',
    website: 'https://airbnb.com',
    industry: 'Travel Marketplace & Web Platforms',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '888 Brannan St' },
    companySize: '6,000+',
    foundedYear: 2008,
    verified: true,
  },
  {
    id: 'comp_uber',
    name: 'Uber',
    slug: 'uber',
    logo: 'https://www.google.com/s2/favicons?domain=uber.com&sz=128',
    description: 'Uber revolutionizes how goods and people move through cities. Powering rides, food delivery, and autonomous freight with high-throughput distributed dispatch engines.',
    website: 'https://uber.com',
    industry: 'Mobility & Marketplace Tech',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '1515 3rd St' },
    companySize: '10,000+',
    foundedYear: 2009,
    verified: true,
  },
  {
    id: 'comp_spotify',
    name: 'Spotify',
    slug: 'spotify',
    logo: 'https://www.google.com/s2/favicons?domain=spotify.com&sz=128',
    description: 'Spotify is the world’s most popular audio streaming subscription service with 600+ million users. Innovators in audio graph algorithms, recommendation AI, and podcaster tools.',
    website: 'https://spotify.com',
    industry: 'Audio Streaming & Recommendation AI',
    location: { city: 'New York', state: 'NY', country: 'United States', address: '4 World Trade Center' },
    companySize: '6,000+',
    foundedYear: 2006,
    verified: true,
  },
  {
    id: 'comp_janestreet',
    name: 'Jane Street',
    slug: 'jane-street',
    logo: 'https://www.google.com/s2/favicons?domain=janestreet.com&sz=128',
    description: 'Jane Street is a quantitative trading firm with a unique focus on technology, intellectual curiosity, and OCaml functional programming to trade in global markets 24 hours a day.',
    website: 'https://janestreet.com',
    industry: 'Quantitative Trading & OCaml Systems',
    location: { city: 'New York', state: 'NY', country: 'United States', address: '250 Vesey St' },
    companySize: '2,500+',
    foundedYear: 2000,
    verified: true,
  },
  {
    id: 'comp_citadel',
    name: 'Citadel',
    slug: 'citadel',
    logo: 'https://www.google.com/s2/favicons?domain=citadel.com&sz=128',
    description: 'Citadel and Citadel Securities engineer high-performance computing, FPGA kernels, and low-latency algorithmic trading systems handling billions of market messages daily.',
    website: 'https://citadel.com',
    industry: 'Algorithmic Trading & Ultra-Low Latency',
    location: { city: 'Miami', state: 'FL', country: 'United States', address: '830 Brickell Plaza' },
    companySize: '3,000+',
    foundedYear: 1990,
    verified: true,
  },
  {
    id: 'comp_databricks',
    name: 'Databricks',
    slug: 'databricks',
    logo: 'https://www.google.com/s2/favicons?domain=databricks.com&sz=128',
    description: 'Databricks is the Data and AI company. More than 10,000 organizations rely on the Databricks Lakehouse Platform to unify data, analytics, and generative AI.',
    website: 'https://databricks.com',
    industry: 'Data & AI Lakehouse Platform',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '160 Spear St' },
    companySize: '7,000+',
    foundedYear: 2013,
    verified: true,
  },
  {
    id: 'comp_snowflake',
    name: 'Snowflake',
    slug: 'snowflake',
    logo: 'https://www.google.com/s2/favicons?domain=snowflake.com&sz=128',
    description: 'Snowflake enables organizations to mobilize data with Snowflake’s Data Cloud. Unifying data lakes, data warehouses, data engineering, and data science workloads.',
    website: 'https://snowflake.com',
    industry: 'Cloud Data Warehouse',
    location: { city: 'Bozeman', state: 'MT', country: 'United States', address: '106 E Babcock St' },
    companySize: '7,000+',
    foundedYear: 2012,
    verified: true,
  },
  {
    id: 'comp_palantir',
    name: 'Palantir Technologies',
    slug: 'palantir',
    logo: 'https://www.google.com/s2/favicons?domain=palantir.com&sz=128',
    description: 'Palantir builds software that empowers organizations to effectively integrate their data, decisions, and operations. Creators of Foundry, Gotham, and AIP (Artificial Intelligence Platform).',
    website: 'https://palantir.com',
    industry: 'Defense, Big Data & Foundry AI',
    location: { city: 'Denver', state: 'CO', country: 'United States', address: '1200 17th St' },
    companySize: '4,000+',
    foundedYear: 2003,
    verified: true,
  },
  {
    id: 'comp_spacex',
    name: 'SpaceX',
    slug: 'spacex',
    logo: 'https://www.google.com/s2/favicons?domain=spacex.com&sz=128',
    description: 'SpaceX designs, manufactures and launches advanced rockets and spacecraft. Building Falcon 9, Starship, and Starlink global low-latency satellite constellation.',
    website: 'https://spacex.com',
    industry: 'Aerospace & Starlink Distributed Networks',
    location: { city: 'Hawthorne', state: 'CA', country: 'United States', address: 'Rocket Road' },
    companySize: '10,000+',
    foundedYear: 2002,
    verified: true,
  },
  {
    id: 'comp_tesla',
    name: 'Tesla',
    slug: 'tesla',
    logo: 'https://www.google.com/s2/favicons?domain=tesla.com&sz=128',
    description: 'Tesla accelerates the world’s transition to sustainable energy with electric vehicles, solar, and integrated renewable energy solutions alongside Full Self-Driving (FSD) neural networks.',
    website: 'https://tesla.com',
    industry: 'Autonomous Vehicles & Clean Energy',
    location: { city: 'Austin', state: 'TX', country: 'United States', address: '1 Tesla Road' },
    companySize: '10,000+',
    foundedYear: 2003,
    verified: true,
  },
  {
    id: 'comp_scaleai',
    name: 'Scale AI',
    slug: 'scale-ai',
    logo: 'https://www.google.com/s2/favicons?domain=scale.com&sz=128',
    description: 'Scale AI provides the data foundation for AI. Powering LLM fine-tuning, RLHF evaluations, autonomous vehicle perception models, and enterprise frontier intelligence.',
    website: 'https://scale.com',
    industry: 'Data Engine for Foundation Models',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '155 5th St' },
    companySize: '1,000+',
    foundedYear: 2016,
    verified: true,
  },
  {
    id: 'comp_github',
    name: 'GitHub',
    slug: 'github',
    logo: 'https://www.google.com/s2/favicons?domain=github.com&sz=128',
    description: 'GitHub is the home for all developers. Millions of developers and companies build, ship, and maintain their software with GitHub Actions, Codespaces, and GitHub Copilot.',
    website: 'https://github.com',
    industry: 'Developer Platform & GitHub Copilot',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '88 Colin P Kelly Jr St' },
    companySize: '3,000+',
    foundedYear: 2008,
    verified: true,
  },
  {
    id: 'comp_discord',
    name: 'Discord',
    slug: 'discord',
    logo: 'https://www.google.com/s2/favicons?domain=discord.com&sz=128',
    description: 'Discord is a voice, video, and text communication service used by hundreds of millions of people to talk and hang out with their friends and communities.',
    website: 'https://discord.com',
    industry: 'Real-Time Voice, Video & Chat',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '444 De Haro St' },
    companySize: '1,000+',
    foundedYear: 2015,
    verified: true,
  },
  {
    id: 'comp_robinhood',
    name: 'Robinhood',
    slug: 'robinhood',
    logo: 'https://www.google.com/s2/favicons?domain=robinhood.com&sz=128',
    description: 'Robinhood’s mission is to democratize finance for all. Offering commission-free investing in US stocks, options, ETFs, and cryptocurrencies with real-time market data.',
    website: 'https://robinhood.com',
    industry: 'Modern Brokerage & Crypto Trading',
    location: { city: 'Menlo Park', state: 'CA', country: 'United States', address: '85 Willow Rd' },
    companySize: '2,500+',
    foundedYear: 2013,
    verified: true,
  },
  {
    id: 'comp_coinbase',
    name: 'Coinbase',
    slug: 'coinbase',
    logo: 'https://www.google.com/s2/favicons?domain=coinbase.com&sz=128',
    description: 'Coinbase builds the cryptoeconomy — a more fair, accessible, efficient, and transparent financial system enabled by crypto. Creators of Coinbase Exchange and the Base L2 network.',
    website: 'https://coinbase.com',
    industry: 'Blockchain Infrastructure & Base L2',
    location: { city: 'Remote Global', state: 'CA', country: 'United States', address: 'Remote First' },
    companySize: '3,500+',
    foundedYear: 2012,
    verified: true,
  },
  {
    id: 'comp_brex',
    name: 'Brex',
    slug: 'brex',
    logo: 'https://www.google.com/s2/favicons?domain=brex.com&sz=128',
    description: 'Brex is the AI-powered spend management platform. Empowering fast-growing companies and enterprises with corporate cards, expense management, travel booking, and bill pay.',
    website: 'https://brex.com',
    industry: 'Corporate Cards & AI Spend Management',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '1283 Howard St' },
    companySize: '1,200+',
    foundedYear: 2017,
    verified: true,
  },
  {
    id: 'comp_notion',
    name: 'Notion',
    slug: 'notion',
    logo: 'https://www.google.com/s2/favicons?domain=notion.so&sz=128',
    description: 'Notion is the connected workspace where teams build docs, manage projects, and organize knowledge with integrated AI search and workflow automation.',
    website: 'https://notion.so',
    industry: 'Connected Workspace & Knowledge Bases',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: '510 Townsend St' },
    companySize: '800+',
    foundedYear: 2013,
    verified: true,
  },
  {
    id: 'comp_cursor',
    name: 'Anysphere (Cursor)',
    slug: 'cursor',
    logo: 'https://www.google.com/s2/favicons?domain=cursor.com&sz=128',
    description: 'Cursor is the AI-first code editor designed for pair programming with frontier AI models. Built by Anysphere to 10x developer speed with full codebase indexing.',
    website: 'https://cursor.com',
    industry: 'AI Code Editor & Developer Tools',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: 'Mission St' },
    companySize: '50+',
    foundedYear: 2022,
    verified: true,
  },
  {
    id: 'comp_perplexity',
    name: 'Perplexity AI',
    slug: 'perplexity',
    logo: 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128',
    description: 'Perplexity AI is a conversational answer engine that delivers accurate, real-time answers with clear source citations powered by web-scale search and LLMs.',
    website: 'https://perplexity.ai',
    industry: 'Conversational Answer Engine & Search',
    location: { city: 'San Francisco', state: 'CA', country: 'United States', address: 'Downtown SF' },
    companySize: '100+',
    foundedYear: 2022,
    verified: true,
  },
  {
    id: 'comp_elevenlabs',
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    logo: 'https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=128',
    description: 'ElevenLabs research and deploys frontier generative voice and audio AI, producing human-quality speech synthesis and dubbing in 30+ languages.',
    website: 'https://elevenlabs.io',
    industry: 'Generative Audio & AI Voice Synthesis',
    location: { city: 'New York', state: 'NY', country: 'United States', address: 'Manhattan' },
    companySize: '150+',
    foundedYear: 2022,
    verified: true,
  },
  {
    id: 'comp_mistral',
    name: 'Mistral AI',
    slug: 'mistral-ai',
    logo: 'https://www.google.com/s2/favicons?domain=mistral.ai&sz=128',
    description: 'Mistral AI is a European AI lab producing top-performing open and commercial frontier large language models (Mistral Large, Codestral, Mixtral 8x22B).',
    website: 'https://mistral.ai',
    industry: 'Open & Frontier LLMs',
    location: { city: 'Paris', state: 'Île-de-France', country: 'France', address: '15 Rue de Richelieu' },
    companySize: '120+',
    foundedYear: 2023,
    verified: true,
  },
  {
    id: 'comp_huggingface',
    name: 'Hugging Face',
    slug: 'huggingface',
    logo: 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
    description: 'Hugging Face is the platform where the machine learning community collaborates on models, datasets, and applications with over 1 million open-source models.',
    website: 'https://huggingface.co',
    industry: 'Open Source AI Hub & Transformers',
    location: { city: 'New York', state: 'NY', country: 'United States', address: 'Brooklyn' },
    companySize: '250+',
    foundedYear: 2016,
    verified: true,
  },
  {
    id: 'comp_roblox',
    name: 'Roblox',
    slug: 'roblox',
    logo: 'https://www.google.com/s2/favicons?domain=roblox.com&sz=128',
    description: 'Roblox is an immersive 3D platform connecting over 70 million daily active users worldwide to play, create, and socialize across virtual worlds.',
    website: 'https://roblox.com',
    industry: 'Immersive 3D Metaverse & Game Engine',
    location: { city: 'San Mateo', state: 'CA', country: 'United States', address: '970 Park Pl' },
    companySize: '2,500+',
    foundedYear: 2004,
    verified: true,
  },
  {
    id: 'comp_canva',
    name: 'Canva',
    slug: 'canva',
    logo: 'https://www.google.com/s2/favicons?domain=canva.com&sz=128',
    description: 'Canva is an Australian visual communication platform with 180+ monthly users empowering everyone to design presentations, video, and websites.',
    website: 'https://canva.com',
    industry: 'Visual Communication & Design Platform',
    location: { city: 'Sydney', state: 'NSW', country: 'Australia', address: '110 Kippax St' },
    companySize: '4,000+',
    foundedYear: 2012,
    verified: true,
  },
  {
    id: 'comp_adobe',
    name: 'Adobe',
    slug: 'adobe',
    logo: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=128',
    description: 'Adobe is the global leader in digital media and digital marketing software. Powering Photoshop, Illustrator, Premiere Pro, and Adobe Firefly generative AI.',
    website: 'https://adobe.com',
    industry: 'Creative Cloud, Firefly AI & PDF',
    location: { city: 'San Jose', state: 'CA', country: 'United States', address: '345 Park Ave' },
    companySize: '10,000+',
    foundedYear: 1982,
    verified: true,
  },
];
